server.port=${PORT:10000}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shramsaathi}
spring.datasource.username=${DB_USER:${DB_USERNAME:root}}
spring.datasource.password=${DB_PASSWORD:rama2004}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
jwt.access-token-expiry-seconds=${JWT_ACCESS_TOKEN_EXPIRY_SECONDS:900}
jwt.refresh-token-expiry-seconds=${JWT_REFRESH_TOKEN_EXPIRY_SECONDS:2592000}
twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.phone.number=${TWILIO_PHONE_NUMBER:}
